# Custom Language File for Launcher Customizer

[ejs.app]
title = "NSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://twitter.com/DebansCommunity/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/DebansCommunity/NSMPLauncher"
supportLink = "https://github.com/DebansCommunity/NSMPLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR NSMP"
welcomeDescription = "Notre mission est de fournir une expérience<br>vanilla ou moddé le plus qualitatif possible."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de rejoindre NSMP."
